# Generated by Django 3.2.5 on 2021-12-02 05:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productID', models.CharField(blank=True, max_length=200, null=True)),
                ('userID', models.CharField(blank=True, max_length=200, null=True)),
                ('traceUniqueID', models.CharField(blank=True, max_length=200, null=True)),
                ('updateType', models.CharField(blank=True, max_length=200, null=True)),
                ('updateTime', models.CharField(blank=True, max_length=200, null=True)),
                ('updateDesc', models.CharField(blank=True, max_length=200, null=True)),
                ('effectiveTime', models.CharField(blank=True, max_length=200, null=True)),
                ('expiryTime', models.CharField(blank=True, max_length=200, null=True)),
                ('req_body', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Subscribtion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_active', models.BooleanField(default=False)),
                ('starts_date', models.DateTimeField(blank=True, null=True)),
                ('ends_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
