# Generated by Django 3.2.5 on 2021-12-02 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_subscribtion_webhookbackup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhookbackup',
            name='effectiveTime',
        ),
        migrations.RemoveField(
            model_name='webhookbackup',
            name='expiryTime',
        ),
        migrations.RemoveField(
            model_name='webhookbackup',
            name='productID',
        ),
        migrations.RemoveField(
            model_name='webhookbackup',
            name='traceUniqueID',
        ),
        migrations.RemoveField(
            model_name='webhookbackup',
            name='updateDesc',
        ),
        migrations.RemoveField(
            model_name='webhookbackup',
            name='updateTime',
        ),
        migrations.RemoveField(
            model_name='webhookbackup',
            name='updateType',
        ),
        migrations.RemoveField(
            model_name='webhookbackup',
            name='userID',
        ),
    ]
