# Generated by Django 3.2.9 on 2023-09-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20230923_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company_banner',
            field=models.ImageField(blank=True, upload_to='vendor/banner/'),
        ),
    ]
