# Generated by Django 3.2.9 on 2023-10-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company_alias',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
