# Generated by Django 3.2.9 on 2023-10-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_company_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='vendor/thumbnail/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company_banner',
            field=models.ImageField(blank=True, null=True, upload_to='vendor/banner/'),
        ),
    ]
