# Generated by Django 3.2.5 on 2021-07-10 10:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('language', models.CharField(blank=True, max_length=120, null=True)),
                ('img_banner', models.ImageField(blank=True, upload_to='content_images/banner/')),
                ('img_poster', models.ImageField(blank=True, upload_to='content_images/poster/')),
                ('img_detail_poster', models.ImageField(blank=True, upload_to='content_images/poster/')),
                ('img_detail_banner', models.ImageField(blank=True, upload_to='content_images/banner/')),
                ('img_trailer', models.ImageField(blank=True, upload_to='content_images/trailer/')),
                ('img_thumbnail', models.ImageField(blank=True, upload_to='content_images/thumbnai/')),
                ('trailer_mp4', models.FileField(blank=True, upload_to='content_file/trailer/mp4/')),
                ('trailer_webm', models.FileField(blank=True, upload_to='content_file/trailer/webm/')),
                ('file_mp4', models.FileField(blank=True, upload_to='content_file/mp4/')),
                ('file_webm', models.FileField(blank=True, upload_to='content_file/webm/')),
                ('timedelta', models.DurationField(blank=True)),
                ('upload_date', models.DateField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ContentGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='WatchedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watched_content', to='core.content')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_content', to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(default='Lorem Ipsum')),
                ('img_banner', models.ImageField(blank=True, upload_to='content_images/banner/')),
                ('img_poster', models.ImageField(blank=True, upload_to='content_images/poster/')),
                ('img_detail_poster', models.ImageField(blank=True, upload_to='content_images/poster/')),
                ('img_detail_banner', models.ImageField(blank=True, upload_to='content_images/banner/')),
                ('img_trailer', models.ImageField(blank=True, upload_to='content_images/trailer/')),
                ('img_thumbnail', models.ImageField(blank=True, upload_to='content_images/thumbnai/')),
                ('trailer_mp4', models.FileField(blank=True, upload_to='content_file/trailer/mp4/')),
                ('trailer_webm', models.FileField(blank=True, upload_to='content_file/trailer/webm/')),
                ('file_mp4', models.FileField(blank=True, upload_to='content_file/mp4/')),
                ('file_webm', models.FileField(blank=True, upload_to='content_file/webm/')),
                ('upload_date', models.DateField(blank=True)),
                ('timedelta', models.DurationField(blank=True, null=True)),
                ('position', models.IntegerField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.content')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='content',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contentcategory'),
        ),
        migrations.AddField(
            model_name='content',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contentgenre'),
        ),
    ]
