# Generated by Django 3.2.5 on 2021-07-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='watch_times',
            field=models.IntegerField(default=1),
        ),
    ]
