# Generated by Django 3.2.5 on 2021-07-11 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_content_watch_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='content_episodes', to='core.content'),
        ),
    ]
