# Generated by Django 3.2.5 on 2022-09-24 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_usersubscribtion'),
        ('core', '0003_alter_episode_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchedcontent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_content', to='users.userprofile'),
        ),
    ]
