# Generated by Django 3.2.9 on 2023-09-23 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20230923_1905'),
        ('core', '0004_alter_watchedcontent_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.profile'),
        ),
        migrations.AddField(
            model_name='episode',
            name='watch_times',
            field=models.IntegerField(default=1),
        ),
    ]
