# Generated by Django 3.2.9 on 2023-09-24 09:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchedcontent',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
