# Generated by Django 3.2.9 on 2023-09-24 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_watchedcontent_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_category', to='core.contentcategory'),
        ),
        migrations.AlterField(
            model_name='content',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_genre', to='core.contentgenre'),
        ),
    ]
