# Generated by Django 3.2.9 on 2023-10-20 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0008_channel_admin_favorite'),
        ('core', '0009_auto_20230924_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor.channel'),
        ),
    ]
