# Generated by Django 3.2.9 on 2023-10-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20231022_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentcategory',
            name='icon',
            field=models.ImageField(blank=True, upload_to='category/icon/'),
        ),
        migrations.AddField(
            model_name='contentgenre',
            name='icon',
            field=models.ImageField(blank=True, upload_to='genre/icon/'),
        ),
    ]
