# Generated by Django 3.2.9 on 2023-10-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20231022_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='core.ContentTag'),
        ),
    ]
