# Generated by Django 3.2.9 on 2023-11-06 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0009_channel_default_channel'),
        ('core', '0014_alter_content_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content', to='vendor.channel'),
        ),
    ]
